### ISSUE TITLE
Improve GeoJSON validator to catch more formatting errors

### ISSUE THREAD

**Issue by grischard** [osmlab/osm-community-index#193]
`CONTRIBUTING.md` doesn't mention the `npm install` step, resulting in this rather unhelpful message:

```
$ npm run test

> osm-community-index@0.4.7 test /Users/stereo/Documents/code/osm-community-index
> npm run build && npm run lint && tap test/*.js


> osm-community-index@0.4.7 build /Users/stereo/Documents/code/osm-community-index
> node build.js && rollup -c

internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'colors/safe'
```
<details>

```
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/stereo/Documents/code/osm-community-index/build.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osm-community-index@0.4.7 build: `node build.js && rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osm-community-index@0.4.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stereo/.npm/_logs/2018-11-04T16_05_57_200Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osm-community-index@0.4.7 test: `npm run build && npm run lint && tap test/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osm-community-index@0.4.7 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stereo/.npm/_logs/2018-11-04T16_05_57_221Z-debug.log
```

</details>

**Comment by grischard** [comment]
Even after `npm install`, I get:

```
npm run test

> osm-community-index@0.4.7 test /Users/stereo/Documents/code/osm-community-index
> npm run build && npm run lint && tap test/*.js


> osm-community-index@0.4.7 build /Users/stereo/Documents/code/osm-community-index
> node build.js && rollup -c

building data
Features:✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:6
      return p.map(function(e) {
               ^

TypeError: p.map is not a function
    at point (/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:6:16)
    at Array.map (<anonymous>)
    at multi (/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:12:16)
    at Array.map (<anonymous>)
    at poly (/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:16:16)
    at geometry (/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:38:29)
    at feature (/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:52:22)
    at parse (/Users/stereo/Documents/code/osm-community-index/node_modules/geojson-precision/index.js:72:16)
    at /Users/stereo/Documents/code/osm-community-index/build.js:60:23
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osm-community-index@0.4.7 build: `node build.js && rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osm-community-index@0.4.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stereo/.npm/_logs/2018-11-04T16_10_38_428Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osm-community-index@0.4.7 test: `npm run build && npm run lint && tap test/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osm-community-index@0.4.7 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stereo/.npm/_logs/2018-11-04T16_10_38_489Z-debug.log
```

**Comment by bhousel** [comment]
> Even after `npm install`, I get this unhelpful message because of an error in my geojson:

I'd like to make this error message friendlier - what did you put into the geojson that caused the issue?  I think you might have gotten a different error message if it didn't validate.

**Comment by grischard** [comment]
> what did you put into the geojson that caused the issue?

It was like the Croatia polygon except I had it as a `Polygon` instead of a `LineString`.

**Comment by bhousel** [comment]
Ok, yeah I switched it back to a Polygon and realized there needs to be an additional array nesting.  Our current GeoJSON schema validator doesn't catch this as an error, that's why you end up with an error later in the code.

We can look into replacing the GeoJSON validator with something better..

* [geojson/schema](https://github.com/geojson/schema) I think is a generator for the json-schema doc that this project currently uses.
* [yagajs/geojson-schema](https://github.com/yagajs/geojson-schema) looks promising, may validate more things with code.

**Comment by grischard** [comment]
In that case, Croatia is wrong too, and I picked the wrong file to copy :)

**Comment by bhousel** [comment]
stale
